title: LNET-Discord Bridge
description: High-performance .NET 9 bridge application documentation
baseurl: "/lnet-discord-bridge"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme settings
theme: just-the-docs
color_scheme: dark

# Just the Docs configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_sort: case_insensitive

# Enable or disable the site search
aux_links:
  "GitHub Repository":
    - "https://github.com/yourusername/lnet-discord-bridge"

aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2024. Educational project for AI-assisted development research."

# Google Analytics (optional)
# ga_tracking: UA-XXXXXXXX-X

# Code highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections for better organization
collections:
  lnet:
    output: true
    permalink: /:collection/:name/
  discord:
    output: true
    permalink: /:collection/:name/
  bridge:
    output: true
    permalink: /:collection/:name/
  deployment:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "lnet"
      type: "pages"
    values:
      layout: "default"
      parent: "LNet Library"
  - scope:
      path: "discord"
      type: "pages"
    values:
      layout: "default"
      parent: "Discord Library"
  - scope:
      path: "bridge"
      type: "pages"
    values:
      layout: "default"
      parent: "Bridge Service"
  - scope:
      path: "deployment"
      type: "pages"
    values:
      layout: "default"
      parent: "Deployment"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md